baseURL = "https://www.geotattoos.com/"
languageCode = "en"
title = "Geo Tattoos - Tattoo Making | Tattoo Removal | Tattoo Training | Tattoo Products"
theme = "tattoo-shop-hugo-theme"

[params]
description = "Geo tattoos, owned by George, is one of Chennai's top tattoo shops. Services include Tattoo Making, Tattoo Removal, and Tattoo Training. We also sell Tattoo Products."
keywords = "Tattoo shops in Chennai, Tattoo shop in Chennai, Tattoo in Chennai, Best Tattoo shop in Chennai, Low cost Tattoo shops in Chennai, Tattoo Making, Tattoo Removal, Tattoo Training, Tattoo Products"
author = "TenSketch"
og_image = "images/og_image.png"

# Configure static directories
staticDir = ["static", "themes/tattoo-shop-hugo-theme/static"]
