backend:   
  name: git-gateway   
  branch: main # Branch to update (optional; defaults to main)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "gallery" # Used in routes, e.g., /admin/collections/gallery
    label: "Latest Tattoos gallery" # Used in the UI
    # widget": "image"
    folder: "content/home_gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
    - label: "Image"
      name: "image"
      required: true
      widget: "image"
      choose_url: true
      media_library:
        config:
          multiple: true
    - label: "Image Title"
      name: "title"
      widget: "string"
      required: true
    - label: "Tags"
      name: "tags"
      default: ["homegal"]
      required: false
      widget: "list"
    - label: "Upload Date"
      name: "date"
      required: false
      widget: "datetime"
    - label: "Draft"
      name: "draft"
      widget: "boolean"
      default: false
      required: false

      