backend:   
  name: git-gateway   
  branch: main # Branch to update (optional; defaults to main)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
# publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

    fields:
      - { name: title, 
          label: Image name , 
          widget: string, 
          required: true }

      - { label: "Image",
          name: "image",
          required: true,
          widget: "image",
          choose_url: true }

      - { label: "Tags",
          name: "tags",
          default: ["blog"],
          required: false,
          widget: "list",
          allow_add: false }
          
      - { label: "Upload Date",
          name: "date",
          required: false,
          widget: "datetime" }
          
      - { label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false }
          
  - name: "gallery" # Used in routes, e.g., /admin/collections/gallery
    label: "Latest Tattoos gallery" # Used in the UI
    # widget": "image"
    folder: "content/latestPics" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    media_library:
      name: cloudinary
      config:
        cloud_name: tensketch285
        api_key: 995746926192923
    fields: # The fields for each document, usually in front matter
      - { label: "Image",
          name: "image",
          required: true,
          widget: "image",
          choose_url: true }
      - { label: "Image name",
          name: "title",
          widget: "string",
          required: true }
      - { label: "Tags",
          name: "tags",
          default: ["galnew"],
          required: false,
          widget: "list",
          allow_add: false }
      - { label: "Upload Date",
          name: "date",
          required: false,
          widget: "datetime" }
      - { label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false }

      